[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan serve --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "nestle-retailer-direct"
type = "web"

[services.environment]
APP_NAME = "Nestle-Retailer-Direct"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
LOG_LEVEL = "info"
BROADCAST_CONNECTION = "log"
FILESYSTEM_DISK = "public"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "database"
CACHE_STORE = "database"
DB_CONNECTION = "pgsql"
